name: Adobe Consulting Services
highlighter: rouge
markdown: kramdown
exclude:  [ Gemfile, Gemfile.lock, README.md, vendor/ ]
#baseurl: /
collections:
  announcements:
    output: false
  acs-aem-commons:
    output: true
  acs-aem-tools:
    output: true
  contributors:
    output: true
gems:
  - jekyll-redirect-from
sass:
    sass_dir: _sass
    style: compressed